#!/usr/bin/env node
// Universal PreToolUse hook: blocks editing protected files.
// Each entry maps a file pattern to an instruction returned to Claude.

// ── Protected files registry ──────────────────────────────────────
// Format: { pattern: instruction }
// Pattern matching: substring match against the file path.
// To add a new protected file, add a new entry below.
const PROTECTED_FILES = {
  // ── AWS ──
  '.aws/config': "Use 'aws configure set' CLI command instead (e.g. 'aws configure set region us-east-1 --profile myprofile').",
  '.aws/credentials': "Use 'aws configure set' CLI command or credential helper tools instead. Never store credentials by direct file editing.",

  // ── SSH keys & config ──
  '.ssh/id_': "SSH private keys must never be edited directly. Use ssh-keygen to generate new keys.",
  '.ssh/authorized_keys': "Use ssh-copy-id or append keys via shell command instead of direct editing.",
  '.ssh/config': "Use shell commands to append/modify SSH config entries instead of direct editing.",

  // ── Shell profiles ──
  '.bashrc': "Use 'echo >> ~/.bashrc' or a shell command to append entries. Direct editing risks breaking the shell.",
  '.zshrc': "Use 'echo >> ~/.zshrc' or a shell command to append entries. Direct editing risks breaking the shell.",
  '.bash_profile': "Use 'echo >> ~/.bash_profile' or a shell command to append entries. Direct editing risks breaking the shell.",
  '.zprofile': "Use 'echo >> ~/.zprofile' or a shell command to append entries. Direct editing risks breaking the shell.",

  // ── Package lockfiles ──
  'package-lock.json': "Lockfiles are generated by package managers. Run 'npm install' to regenerate.",
  'yarn.lock': "Lockfiles are generated by package managers. Run 'yarn install' to regenerate.",
  'Gemfile.lock': "Lockfiles are generated by package managers. Run 'bundle install' to regenerate.",
  'poetry.lock': "Lockfiles are generated by package managers. Run 'poetry lock' to regenerate.",
};
// ──────────────────────────────────────────────────────────────────

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
  let filePath;
  try {
    const data = JSON.parse(input);
    filePath = data?.tool_input?.file_path;
  } catch {
    process.exit(0);
  }

  if (!filePath) process.exit(0);

  for (const [pattern, instruction] of Object.entries(PROTECTED_FILES)) {
    if (filePath.includes(pattern)) {
      process.stderr.write(`BLOCKED: Editing '${filePath}' is not allowed (matches protected pattern '${pattern}'). ${instruction}\n`);
      process.exit(2);
    }
  }

  process.exit(0);
});
