#!/usr/bin/env node
// Universal PreToolUse hook: blocks editing protected files.

const path = require('path');
const os = require('os');
const fs = require('fs');

// ── HOME-relative protected files ─────────────────────────────────
// Matched only when the file path is under the user's home directory.
// Format: { pattern: instruction }
// Pattern matching: home-relative path must START WITH the pattern (anchored).
// These cause a hard block (exit 2).
const HOME_PROTECTED_FILES = {
  // ── AWS directory (all files) ──
  '.aws/': "AWS configuration directory is protected. Use 'aws configure' CLI or credential helper tools instead of direct file editing.",

  // ── SSH directory (all files) ──
  '.ssh/': "SSH directory is protected. Use ssh-keygen, ssh-copy-id, or shell commands instead of direct file editing.",
};

// ── HOME-relative warned files ─────────────────────────────────────
// Matched only when the file path is under the user's home directory.
// These allow the edit but inject a systemMessage requiring explicit permission.
// Pattern matching: exact basename match.
const HOME_WARN_FILES = {
  // ── Shell profiles ──
  '.bashrc': "This is a shell profile under the user's home directory. You MUST ask the user for explicit permission before modifying this file.",
  '.zshrc': "This is a shell profile under the user's home directory. You MUST ask the user for explicit permission before modifying this file.",
  '.bash_profile': "This is a shell profile under the user's home directory. You MUST ask the user for explicit permission before modifying this file.",
  '.zprofile': "This is a shell profile under the user's home directory. You MUST ask the user for explicit permission before modifying this file.",
};

// ── Basename-protected files ───────────────────────────────────────
// Matched by exact filename anywhere in the filesystem.
// Format: { filename: instruction }
const BASENAME_PROTECTED_FILES = {
  // ── Package lockfiles ──
  'package-lock.json': "Lockfiles are generated by package managers. Run 'npm install' to regenerate.",
  'yarn.lock': "Lockfiles are generated by package managers. Run 'yarn install' to regenerate.",
  'pnpm-lock.yaml': "Lockfiles are generated by package managers. Run 'pnpm install' to regenerate.",
  'Gemfile.lock': "Lockfiles are generated by package managers. Run 'bundle install' to regenerate.",
  'poetry.lock': "Lockfiles are generated by package managers. Run 'poetry lock' to regenerate.",
  'Cargo.lock': "Lockfiles are generated by package managers. Run 'cargo build' to regenerate.",
  'go.sum': "Lockfiles are generated by package managers. Run 'go mod tidy' to regenerate.",
  'composer.lock': "Lockfiles are generated by package managers. Run 'composer install' to regenerate.",

};
// ──────────────────────────────────────────────────────────────────

// Resolve a file path fully: follow symlinks if the file exists,
// otherwise fall back to path.resolve() for normalization.
function resolvePath(filePath) {
  try {
    return fs.realpathSync(filePath);
  } catch {
    return path.resolve(filePath);
  }
}

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
  let filePath;
  try {
    const data = JSON.parse(input);
    filePath = data?.tool_input?.file_path;
  } catch {
    process.exit(0);
  }

  if (!filePath) process.exit(0);

  // Resolve symlinks and normalize path components (prevents traversal bypass).
  filePath = resolvePath(filePath);

  // Check home-relative rules
  const homedir = os.homedir();
  const homedirWithSep = homedir + path.sep;
  if (filePath === homedir || filePath.startsWith(homedirWithSep)) {
    const homeRelative = filePath.startsWith(homedirWithSep)
      ? filePath.slice(homedirWithSep.length)
      : '';

    for (const [pattern, instruction] of Object.entries(HOME_PROTECTED_FILES)) {
      if (homeRelative.startsWith(pattern)) {
        process.stderr.write(`BLOCKED: Editing '${filePath}' is not allowed (matches protected pattern '${pattern}'). ${instruction}\n`);
        process.exit(2);
      }
    }

    for (const [pattern, warning] of Object.entries(HOME_WARN_FILES)) {
      if (path.basename(filePath) === pattern) {
        process.stdout.write(JSON.stringify({ systemMessage: warning }) + '\n');
        process.exit(0);
      }
    }
  }

  // Check basename-protected files (exact basename match)
  const basename = path.basename(filePath);
  if (BASENAME_PROTECTED_FILES[basename]) {
    process.stderr.write(`BLOCKED: Editing '${filePath}' is not allowed ('${basename}' must not be edited directly). ${BASENAME_PROTECTED_FILES[basename]}\n`);
    process.exit(2);
  }

  process.exit(0);
});
